# Server-side deployment configuration for SSE transport
# Simplified version for use with existing reverse proxy (Nginx Proxy Manager, Traefik, Caddy, etc.)
# This exposes the MCP server on port 8000 - configure your reverse proxy to handle HTTPS/SSL

version: '3.9'

services:
  # Kleinanzeigen MCP Server (SSE mode)
  kleinanzeigen-mcp:
    image: kleinanzeigen-mcp:latest
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: kleinanzeigen-mcp
    environment:
      # Enable SSE transport mode
      TRANSPORT_MODE: sse
      
      # Server configuration
      HOST: 0.0.0.0
      PORT: 55122
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      
      # Authentication (optional - can be handled by reverse proxy)
      MCP_API_KEY: ${MCP_API_KEY}
    ports:
      - "${MCP_PORT:-8000}:8000"  # Expose for reverse proxy
    restart: unless-stopped
    networks:
      - mcp-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mcp-network:
    driver: bridge
